import "./globals.css";
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import localFont from "next/font/local";

// Next UI
import { Providers } from "./providers";

// Components
import Navbar from "./Navbar";
import { Toaster } from "react-hot-toast";
import AuthProvider from "./auth/provider";

const inter = Inter({ subsets: ["latin"] });

const montSerrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500"],
});

const poppins = localFont({
  src: "../public/fonts/poppins-regular-webfont.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={poppins.className}>
        <AuthProvider>
          <Toaster
            toastOptions={{
              duration: 2000,
            }}
          />
          <Providers>
            <Navbar />
            <main className="px-[4vw] py-[2vh]">{children}</main>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
