import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Next UI
import { Providers } from "./providers";

// Components
import Navbar from "./Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main className="px-[4vw] py-[2vh]">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
